jobs:
  darkube_build_torobjan_erfanclash20178_calm_moon_hamravesh_c11:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: registry.hamdocker.ir/erfanclash20178-calm-moon/torobjan
      DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout commit
        uses: actions/checkout@v4

      - name: darkube-cli build and push
        run: |
          darkube build --push \
            -t "${IMAGE_NAME}:${GITHUB_SHA:0:7}" \
            -t "${IMAGE_NAME}:${GITHUB_REF_NAME}" \
            --docker-auth-config "${DOCKER_AUTH_CONFIG}" \
            --workdir . \
            --file ./Dockerfile \
            --build-context .

on:
  push:
    branches:
      - main
